"""POST /api/fix endpoint for GitHub PR creation."""

from fastapi import APIRouter, Header, HTTPException, status, Depends

try:
    from github import Github, GithubException
except ImportError:
    Github = None

from app.models.task import FixRequest, FixResponse, PRInfo
from app.core.config import Settings
from app.core.logging import logger
from app.dependencies import get_settings, get_analytics_store
from app.db.analytics_store import AnalyticsStore
from app.services.analytics import track_event


router = APIRouter(prefix="/api", tags=["GitHub Integration"])


@router.post("/fix", response_model=FixResponse)
async def create_fix_pr(
    request: FixRequest,
    authorization: str = Header(None),
    settings: Settings = Depends(get_settings),
    analytics_store: AnalyticsStore = Depends(get_analytics_store),
) -> FixResponse:
    """
    Create a GitHub PR with AI-generated security patches.
    
    Args:
        request: FixRequest with repo, file, patch code, etc.
        authorization: Bearer token (takes precedence over body token)
        settings: App settings
    
    Returns:
        FixResponse with PR details or error
    """
    
    if settings is None:
        from app.core.config import settings as default_settings
        settings = default_settings
    
    if not Github:
        return FixResponse(
            success=False,
            error_message="PyGithub not installed",
        )
    
    # Resolve GitHub token
    github_token = None
    if authorization and authorization.startswith("Bearer "):
        github_token = authorization[7:]  # Remove "Bearer " prefix
    elif hasattr(request, "github_token"):
        github_token = getattr(request, "github_token")
    elif settings.GITHUB_TOKEN:
        github_token = settings.GITHUB_TOKEN
    
    if not github_token:
        await track_event(analytics_store, "fix_failed", {"repo": request.repo_name, "reason": "missing_token"})
        return FixResponse(
            success=False,
            error_message="GitHub token required (Authorization header or GITHUB_TOKEN env var)",
        )
    
    logger.info(f"[Fix] Creating PR for {request.repo_name}")
    
    try:
        # Authenticate
        gh = Github(github_token)
        repo = gh.get_repo(request.repo_name)
        
        logger.info(f"[Fix] Authenticated to {request.repo_name}")
        
        # Get base branch SHA
        base_branch = repo.get_branch(request.base_branch)
        base_sha = base_branch.commit.sha
        
        # Create fix branch
        branch_name = f"security-fix/{request.vulnerability_name}"
        
        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_sha,
            )
            logger.info(f"[Fix] Created branch {branch_name}")
        except GithubException as e:
            if e.status == 422:  # Branch already exists
                logger.warning(f"[Fix] Branch {branch_name} already exists; reusing")
            else:
                raise
        
        # Get file and update it
        file_obj = repo.get_contents(request.file_path, ref=branch_name)
        
        repo.update_file(
            request.file_path,
            f"Security Fix: {request.vulnerability_name}",
            request.patched_code,
            file_obj.sha,
            branch=branch_name,
        )
        
        logger.info(f"[Fix] Updated {request.file_path} on {branch_name}")
        
        # Create PR
        pr_title = f"Security Auto-Fix: {request.vulnerability_name}"
        pr_body = f"""## Automated Security Fix

This pull request applies an AI-generated security patch for:

**Vulnerability:** {request.vulnerability_name}

**File:** `{request.file_path}`

### Important

⚠️ **Please review this patch carefully before merging.**

- The patch was auto-generated by our AI security analyzer
- Test thoroughly in your environment
- Ensure the fix maintains intended functionality
- Review the vulnerability details in the description

---

**Generated by:** VulnSentinel Security Bot
"""
        
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=request.base_branch,
        )
        
        logger.info(f"[Fix] Created PR #{pr.number}")

        await track_event(
            analytics_store,
            "fix_pr_created",
            {"repo": request.repo_name, "pr_number": pr.number},
        )
        
        return FixResponse(
            success=True,
            pull_request=PRInfo(
                pr_number=pr.number,
                pr_url=pr.html_url,
                branch_name=branch_name,
            ),
        )
    
    except GithubException as e:
        logger.error(f"[Fix] GitHub API error: {str(e)}")
        await track_event(
            analytics_store,
            "fix_failed",
            {"repo": request.repo_name, "reason": "github_api", "status": e.status},
        )
        
        if e.status == 404:
            detail = f"Repository or branch not found. Verify {request.repo_name} and {request.base_branch} exist."
        else:
            detail = f"GitHub API error: {str(e)}"
        
        return FixResponse(
            success=False,
            error_message=detail,
        )
    
    except Exception as e:
        logger.error(f"[Fix] Unexpected error: {str(e)}")
        await track_event(
            analytics_store,
            "fix_failed",
            {"repo": request.repo_name, "reason": "unexpected"},
        )
        return FixResponse(
            success=False,
            error_message=f"Unexpected error: {str(e)}",
        )
